name: CI/CD

on:
  push:
    branches:
      - release_v52
      - main
      # - master
    # pull_request:
    #   branches:
    #     - master

env:
  JAVA_VERSION: "11.x"
  FLUTTER_VERSION: "2.10.4"
  FLUTTER_CHANNEL: "stable"
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  flutter_test:
    name: Run Flutter assigned build appbundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}

      # Creating the key.properties file
      - run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_STORE }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}

      # Decoding base64 key into a file
      - run: echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > android/app/key.jks

      # Get dependencies and make assigned appbundle
      - run: | 
          flutter pub get
          flutter build appbundle
      # Make appbundle downloadable
      - name: Upload artefato
        uses: actions/upload-artifact@v2
        with:
          name: release_v49_appbundle
          path: build/app/outputs/bundle/release



